# Generated by Django 4.1.5 on 2023-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255)),
                ('pw_hash', models.CharField(max_length=500)),
                ('pfp_id', models.CharField(default=False, max_length=500)),
                ('curr_currency', models.CharField(default='EUR/USD', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField(default=15000)),
                ('test', models.PositiveIntegerField(default=15000)),
            ],
        ),
    ]
