# Generated by Django 4.1.5 on 2023-01-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp_id',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
