# Generated by Django 4.1.5 on 2023-01-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_pfp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currCurrency',
            field=models.CharField(default='EUR/USD', max_length=10),
        ),
    ]
