# Generated by Django 4.1.5 on 2023-01-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isNewUser',
            field=models.BooleanField(default=1),
        ),
    ]
