# Generated by Django 4.1.5 on 2023-01-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_currcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currCurrency',
            field=models.CharField(default='EUR/USD', max_length=12),
        ),
    ]
