# Generated by Django 4.1.5 on 2023-01-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predictingUp', models.BooleanField()),
                ('price_at_trade', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(auto_now_add=True)),
                ('profit', models.PositiveIntegerField()),
                ('investAmount', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='users.user')),
            ],
        ),
    ]
