# Generated by Django 4.1.5 on 2023-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='price_at_trade',
            field=models.FloatField(),
        ),
    ]
