# Generated by Django 4.1.5 on 2023-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_price_at_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
